//
// Created by jbruchanov on 29/03/17.
//

#ifndef NATIVEIMAGEAPP_ERRORS_H
#define NATIVEIMAGEAPP_ERRORS_H

#define NO_ERR 0
#define CANT_OPEN_FILE -1
#define OUT_OF_MEMORY -2
#define NOT_SAME_RESOLUTION -201
#define INVALID_BITMAP_FORMAT -202

#endif //NATIVEIMAGEAPP_ERRORS_H
