/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scurab_andriod_nativeimage_JPEGImage */

#ifndef _Included_com_scurab_andriod_nativeimage_JPEGImage
#define _Included_com_scurab_andriod_nativeimage_JPEGImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage__1init
        (JNIEnv *, jobject, jint);

/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    _loadImage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage__1loadImage
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    _getMetaData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage__1getMetaData
        (JNIEnv *, jobject);

/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    _dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage__1dispose
        (JNIEnv *, jobject);

/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    _setPixels
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT jint JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage__1setPixels
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    _rotate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage__1rotate
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
