/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scurab_andriod_nativeimage_NativeImage */

#ifndef _Included_com_scurab_andriod_nativeimage_NativeImage
#define _Included_com_scurab_andriod_nativeimage_NativeImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scurab_andriod_nativeimage_NativeImage
 * Method:    _init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scurab_andriod_nativeimage_NativeImage__1init
(JNIEnv *, jobject, jint);

/*
 * Class:     com_scurab_andriod_nativeimage_NativeImage
 * Method:    _loadImage
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_scurab_andriod_nativeimage_NativeImage__1loadImage
        (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_scurab_andriod_nativeimage_NativeImage
 * Method:    _saveImage
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_scurab_andriod_nativeimage_NativeImage__1saveImage
        (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_scurab_andriod_nativeimage_NativeImage
 * Method:    _getMetaData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scurab_andriod_nativeimage_NativeImage__1getMetaData
        (JNIEnv *, jobject);

/*
 * Class:     com_scurab_andriod_nativeimage_NativeImage
 * Method:    _dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scurab_andriod_nativeimage_NativeImage__1dispose
(JNIEnv *, jobject);

/*
 * Class:     com_scurab_andriod_nativeimage_NativeImage
 * Method:    _setPixels
 * Signature: (Ljava/lang/Object;IIII)I
 */
JNIEXPORT jint JNICALL Java_com_scurab_andriod_nativeimage_NativeImage__1setPixels
        (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     com_scurab_andriod_nativeimage_NativeImage
 * Method:    _rotate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_scurab_andriod_nativeimage_NativeImage__1rotate
(JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_scurab_andriod_nativeimage_NativeImage
 * Method:    _applyEffect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_com_scurab_andriod_nativeimage_NativeImage__1applyEffect
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
