//
// Created by scurab on 29/03/17.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_scurab_andriod_nativeimage_JPEGImage */

#ifndef _Included_com_scurab_andriod_nativeimage_JPEGImage
#define _Included_com_scurab_andriod_nativeimage_JPEGImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    loadImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage_loadImage
(JNIEnv *, jobject, jstring);

/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    getDetails
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage_getDetails
        (JNIEnv *, jobject);

/*
 * Class:     com_scurab_andriod_nativeimage_JPEGImage
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_scurab_andriod_nativeimage_JPEGImage_dispose
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
